### PR TITLE
WIP: Initial sketch of new lifecycle hooks API

### PR DESCRIPTION
**Pull request by DRMacIver**
The current executors API, as well as being totally undocumented, is rather crude and causes problems with how it determines if something is "supposed" to be an executor and whether to execute hooks on it. This causes problems like #491 and #198.

One option would be to require a specific lifecycle superclass, but that runs into a number of namespacing problems and I'd generally like to avoid introducing an expectation to subclass into Hypothesis's API wherever humanly possible.

This PR sketches an alternative approach based on using decorators  to explicitly annotate methods as being part of the life cycle of the test. These can either use the name of the method if it matches a lifecycle step, or they can specify a completely different method as being part of a lifecycle. This solves the namespacing problem by putting step names in a completely different namespace from normal methods, while still allowing people to use it fairly conveniently in the common case.

Another useful feature of this is that it separates lifecycles from class based testing by allowing you to specify an entirely different object as the lifecycle recipient. This has the bonus feature that it allows you to turn this off when it's causing problems.

The set of hooks provided is designed to be a very minimal implementation which only recreates the subset of the executors functionality that I believe to be used in practice, and longer term a more extensive set of hooks should be implemented.

This is very much not ready to merge. It needs more testing and any documentation, but I'd like to put this out there for general commentary on the API and thoughts about the approach and desiderata.

### CODE REVIEW

**Comment by DRMacIver** [comment]
I have switched this over to a less fundamentally weird API. We now just have a LifeCycle type users can subclass.

This is protected from the normal problems with subclassing by yelling at people if they add any methods to the subclasses that are not prefixed with underscore, which allows us to freely add more hooks in future.

This is still a sketch and feedback would still be appreciated.

**Comment by Zac-HD** [comment]
I don't have enough experience with class-based testing to provide useful feedback on the design of the API.  Reading through the linked issues gives me a pretty clear sense of what this improves though (and reading the existing docs made me shiver at the magic names...).  If the tests are at all a typical use of the API, it looks pretty clean and easy to use to me.

As you note more documentation is needed though.  I'd also like to have the pyformat changes broken out into a separate commit, though staying in the pull is fine.

**Comment by DRMacIver** [comment]
> . I'd also like to have the pyformat changes broken out into a separate commit, though staying in the pull is fine.

I think that's just because this pull is against an old version of master. I'll fix that.

**Comment by DRMacIver** [comment]
Right. This has now been updated to be based off current master and also semi-work.

**Comment by Zac-HD** [comment]
From [this comment](https://github.com/HypothesisWorks/hypothesis-python/issues/292#issuecomment-189703510), should I expect this change to fix the regression in #292?

**Comment by Zac-HD** [comment]
Related to #163.

**Comment by DRMacIver** [comment]
I'm going to close this for now. I may get around to resurrecting it, but probably not any time soon.

**Pull request closed without merging**
