### PR TITLE
Link to new GitHub repo

### PR DESCRIPTION
**Pull request by untitaker**
git grep -l DRMacIver/hypothesis | xargs sed -i 's/DRMacIver\/hypothesis/HypothesisWorks\/hypothesis-python/g'

### CODE REVIEW

**Comment by DRMacIver** [comment]
Oops! Good point Thanks.

**Comment by DRMacIver** [comment]
Oops. I wondered it that might happen. Line length problem is causing travis to fail.

Incidentally you can just update scripts/header.py and run "make format" and it will update the rest of the repo for you. (make lint and make check-format respectively will run the two failing tasks)

**Comment by untitaker** [comment]
I updated the header, but I think the new URL to CONTRIBUTING.rst exceeds the line length limit on its own.

**Comment by DRMacIver** [comment]
I'd be happy to just change it to say CONTRIBUTING.rst instead of the full URL.

**Comment by untitaker** [comment]
I give up. Your "reproducible" test environment assumes the `en_GB` locale to be enabled on the system.

**Comment by DRMacIver** [comment]
Interesting progression.

1. Give me a hard time about my build not making enough assumptions about the system it's on
2. Give me a hard time about my build making assumptions about the system it's on

You're right that en_GB is probably a bad choice. I'll probably fix that, but have you considered that maybe the correct response to "this project author has chosen a different set of trade offs than I have in response to a difficult problem" is not a good reason to give them a hard time over it?

**Comment by untitaker** [comment]
How is "use the system Python" making assumptions?

And I'm sorry, it's a bit depressing when you're trying to get a drive-by contribution working (copy-pasting commands from the Makefile initially) and your opinion is "duly noted and ignored".

On 29 April 2016 08:22:46 CEST, "David R. MacIver" <notifications@github.com> wrote:
>Interesting progression.
>
>1. Give me a hard time about my build not making enough assumptions
>about the system it's on
>2. Give me a hard time about my build making assumptions about the
>system it's on
>
>You're right that en_GB is probably a bad choice. I'll probably fix
>that, but have you considered that maybe the correct response to "this
>project author has chosen a different set of trade offs than I have in
>response to a difficult problem" is not a good reason to give them a
>hard time over it?
>
>---
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/HypothesisWorks/hypothesis-python/pull/315#issuecomment-215636378

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DRMacIver** [comment]
>  How is "use the system Python" making assumptions?

Because thanks to downstream packagers, the system python is routinely in a completely broken state. I'll grant that the format task could probably use it, but most of the rest couldn't. The build is designed to make Hypothesis easy to develop in a way that copes with the realities of the Python ecosystem install base being a complete clusterfuck. 

> And I'm sorry, it's a bit depressing when you're trying to get a drive-by contribution working (copy-pasting commands from the Makefile initially) and your opinion is "duly noted and ignored".

You're right, that was unnecessarily rude phrasing of me. I apologise for it.

But the Hypothesis build is the culmination of dealing with a *great deal* of pain, and it is very well optimised for the problems I actually have to deal with. It works well for drive by contributions with a little bit of initial overhead (setting aside the en\_GB issue, which I've now fixed), and the fact that it offends your aesthetic preferences to have it run in a controlled environment *really* doesn't rate compared to actually solving my actual problems.

**Pull request closed without merging**
