### PR TITLE
Rename classes whose name starts with Test

### PR DESCRIPTION
**Pull request by DRMacIver**
This causes pytest warnings because they look like they're
supposed to be unittest tests, but they have an __init__ which
stops them being picked up as such.

### CODE REVIEW

**Comment by alexwlchan** [comment]
I'll check this fixes all the warnings when CI finishes.

Assuming these are the only outstanding warnings, can/should we add a flag to pytest to turn any pytest warnings into errors?

**Comment by DRMacIver** [comment]
I started to say "That's a good idea, we should do that" then discovered that it's already *supposed* to be doing that. tox.ini (which pytest is supposed to pick up config from) adds the --strict flag, which is supposed to turn warnings into errors. I wonder what's going on?

**Comment by alexwlchan** [comment]
Looks like the use of "warning" in the pytest docs doesn't mean what you might expect, this is a documentation bug: https://github.com/pytest-dev/pytest/issues/1381

**Comment by DRMacIver** [comment]
I see. Sigh.

In that case it looks like the answer is "No, we can't do that easily"?

**Comment by alexwlchan** [comment]
Yep. At best, we can have pytest turn warnings emitted from the code under test into errors, but not those provided by pytest-warnings at the end of the test. 😕 

It sounds like there might be plans afoot to change this in a future version of pytest, but nothing we can do right now: https://github.com/pytest-dev/pytest/issues/1173

**Pull request merged**
