### PR TITLE
Fix use of deprecated --no-use-wheel flag in tests

### PR DESCRIPTION
**Pull request by DRMacIver**

### CODE REVIEW

**Comment by alexwlchan** [comment]
Failure looks unrelated, I've restarted the job.

**Comment by alexwlchan** [comment]
Blergh, GitHub, did we really need to trigger another CI run for that merge commit? This would have merged cleanly, le sigh.

**Comment by DRMacIver** [comment]
I think that's a function of protected branches - github doesn't let them to be merged to unless it can be a fast forward.

**Comment by alexwlchan** [comment]
CI failure looks spurious. I meant to start that individual task; accidentally restarted the whole job. Oh well.

I’ll raise an issue for the broken test – it’s been flakey several times.

**Pull request merged**
