### PR TITLE
Build requirements files using pip-tools, reduce the size of the tools virtualenv

### PR DESCRIPTION
**Pull request by alexwlchan**
This comes from a frustration from reviewing #608, where we're unable to trim requirements.txt-like files as much as we might like, because it's not clear what's a top-level requirement vs. a dependency.

This patch flips them over to use [pip-tools](https://github.com/jazzband/pip-tools) for easier dependency management.

### CODE REVIEW

**Comment by DRMacIver** [comment]
How is this going to interact with pyup pull requests?

**Comment by DRMacIver** [comment]
(That sounded overly negative. I'm in favour of the idea and think it's a good one, I'd just like to make sure we get the best of both)

**Comment by alexwlchan** [comment]
> How is this going to interact with pyup pull requests?

I don’t know, I’m going to find out.

With ✨ SCIENCE ✨.

**Comment by alexwlchan** [comment]
Okay, let’s wait to see how pyup handles this repo: https://github.com/alexwlchan/pyup-testing

**Comment by alexwlchan** [comment]
We have an answer – they play fine together. :D

https://github.com/alexwlchan/pyup-testing/pull/2/files

**Comment by alexwlchan** [comment]
I’ve pulled across the other change from #608, so this now replaces that PR. Hopefully CI will pass shortly and then this will be ready for review.

**Comment by DRMacIver** [comment]
though that does mean we're effectively editing an auto generated file, right? It'd be nice if there were some build step that checks that the two things line up. Though I'm not sure exactly what that would look like without recreating pyup's logic, so maybe best not.

**Comment by alexwlchan** [comment]
> though that does mean we're effectively editing an auto generated file, right? It'd be nice if there were some build step that checks that the two things line up.

That logic would be "run pip-compile, then `git diff --exit-code`".

I can put in a test for that if you'd really like, but the underlying logic is "what's the latest version on PyPI", so the only time I'd expect it to fail (barring bugs in pip-tools or pyup) would be in a window where pyup had opened a PR and we hadn't merged it yet.

**Comment by DRMacIver** [comment]
> I can put in a test for that if you'd really like, but the underlying logic is "what's the latest version on PyPI", so the only time I'd expect it to fail (barring bugs in pip-tools or pyup) would be in a window where pyup had opened a PR and we hadn't merged it yet.

Yeah, which isn't a good thing to have fail. I think not having it be checked is probably better, and I can't actually point to anything wrong with doing it this way, I'm just a little weirded out by it (which is not sufficient motivation tor reject the concept when it's obviously better) :-)

**Comment by Zac-HD** [comment]
What happens when one of our [transitive] dependencies adds a new dependency?  Removes a dependency?  I think we should have a test in CI that nothing is missing, or present but no longer needed.

**Comment by alexwlchan** [comment]
I’ve added a Make task for updating the `requirements.txt` files, and a build check that the dependency tree is still correct (e.g. if you've added a new dependency, as I just have).

**Comment by alexwlchan** [comment]
Okay, I think this is finally passing tests. Needs a cleanup, and might unblock some problems on #515.

**Comment by alexwlchan** [comment]
I’m going to close and reopen this, because CI seems to have lost it.

**Comment by alexwlchan** [comment]
Okay, I’ve tidied up and rebased against master, and I think CI is passing now.

This breaks every time we merge a pyup pull request, so I’ll be merging as soon as tests pass, because I’m bored of playing catchup. 😛

**Comment by alexwlchan** [comment]
Wargh flakey tests.

**Comment by alexwlchan** [comment]
@DRMacIver Can I get a review and a green tick please? :)

**Comment by Zac-HD** [comment]
LGTM.  I suggest merging any pyup pulls, then rebasing and merging this pretty quickly 😉

**Comment by alexwlchan** [comment]
Okay, rebased for hopefully the final time!

**Pull request merged**
