### PR TITLE
Add additional parameters to fractions and decimals strategies.

### PR DESCRIPTION
**Pull request by mulkieran**
Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
This is a first attempt to address #187. I think it needs some further thought, but I'ld like to trigger the CI with it.

**Comment by DRMacIver** [comment]
Thanks for doing this!

This looks pretty good to me, pending CI checks. Do you have specific things in mind you'd like further thought on?

**Comment by DRMacIver** [comment]
(Implicit question above: And can I help by answering any questions you have?)

**Comment by mulkieran** [comment]
Thanks for the offer! I'm wondering if it would be better to make a class for the fractions() strategy, like the various classes for integers strategies. (I'm failing tests across the board, so I'ld better dig into that for a bit.) Also, my version of fractions() is the only basic strategy that uses higher-order strategies, and I'm wondering if that might spell trouble, somehow.

**Comment by DRMacIver** [comment]
I'm travelling at the moment so responses will be a little delayed, but don't worry I'm not ignoring you. :-)

> Also, my version of fractions() is the only basic strategy that uses higher-order strategies, and I'm wondering if that might spell trouble, somehow.

This is more of a historical artifact than something you need to worry about. It *used* to be the case that this would indeed spell heaps of trouble. Now it's totally fine and not something you need to worry about.

If you felt like it you could dig into how to use the Conjecture API directly and save a few object allocations, table lookups, function calls, etc. It won't be very complicated, and it will save some constant factors, but I wouldn't worry about it overly if I were you.

**Comment by mulkieran** [comment]
@DRMacIver I think I'll rest on this version, it doesn't seem that important to use the Conjecture API directly. Let me know what you think. Thanks.

**Comment by DRMacIver** [comment]
Hi,

Sorry, I seem to have dropped the ball on this PR, which was not my intention!

I think it looks pretty good, and the build is green. Are you happy for me to merge it or is there more you want to do on it / questions you need answered?

**Comment by mulkieran** [comment]
Thanks. I think I am satisfied w/ it for now.

**Comment by DRMacIver** [comment]
Great. Thanks for the good work!

**Pull request merged**
