### PR TITLE
Add a description to hs-dbus-signature entry

### PR DESCRIPTION
**Pull request by mulkieran**
For appearance and convenience.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by Zac-HD** [comment]
Close-and-reopen to prod circleci into action...

**Comment by alexwlchan** [comment]
I think this came amid setuptools problems. Closing and reopening for a second time to trigger a new round of builds.

**Comment by Zac-HD** [comment]
Once more with feeling...

**Comment by Zac-HD** [comment]
Hmm, maybe rebasing on master will help.

**Comment by alexwlchan** [comment]
Inspecting the tracebacks, it looks like maybe those jobs were caught with the setuptools version that couldn’t be installed in a clean environment. I’ve restarted the jobs; next step after that is blowing away the build caches.

**Comment by alexwlchan** [comment]
🎉

**Pull request merged**
