### PR TITLE
Typecasted ENCODING_TABLE array to list

### PR DESCRIPTION
**Pull request by amanharitsh123**

### CODE REVIEW

**Comment by DRMacIver** [comment]
Thanks for the patch! But I'm not really sure what you're trying to do here. Could you elaborate on why this is useful?

**Comment by amanharitsh123** [comment]
This PR is in response to issue #1608

**Comment by DRMacIver** [comment]
I'm afraid that doesn't help me understand much, as we don't have an issue 1608 - our highest issue number is only 883!

**Comment by amanharitsh123** [comment]
Can u please have a look on this https://github.com/python/typeshed/issues/1608

**Comment by DRMacIver** [comment]
Oh, I see. That makes sense, but I'm afraid I think this is entirely the wrong solution. The problem here isn't that Hypothesis is using array - array is the correct type to use here - the problem is that mypy doesn't seem to understand arrays.

**Comment by amanharitsh123** [comment]
Oh i see...well thank you for the guidance :-)

**Pull request closed without merging**
