### PR TITLE
Add attrs & argon2_cffi

### PR DESCRIPTION
**Pull request by hynek**
Some humble additions. :)

### CODE REVIEW

**Comment by Zac-HD** [comment]
🎉

There's a certain elegance in Hypothesis using Attrs and Attrs using Hypothesis 😜

**Comment by hynek** [comment]
Synergy! ⚡️

**Comment by DRMacIver** [comment]
> There's a certain elegance in Hypothesis using Attrs and Attrs using Hypothesis 😜

Though it did turn out to indirectly be one of the causes of the packaging problems on anaconda recently. :-)

**Comment by hynek** [comment]
Cool, lets break Debian next! ☠️

**Pull request merged**
