### PR TITLE
Correct date in changelog

### PR DESCRIPTION
**Pull request by Zac-HD**
Ping @DRMacIver; I've cancelled the other build.

### CODE REVIEW

**Comment by DRMacIver** [comment]
Looks like [it failed in your new changelog checks](https://travis-ci.org/HypothesisWorks/hypothesis-python/jobs/232380591).

**Comment by DRMacIver** [comment]
Relatedly, it would be nice if it had a better error message there :-)

**Comment by Zac-HD** [comment]
Yep, turns out I shouldn't sort version numbers as strings - it only works when they have the same number of digits in each part, which was true of everything matched by the regex until I removed some broken links after proposing the change.

And yes, better error message incoming too.

**Comment by DRMacIver** [comment]
> Yep, turns out I shouldn't sort version numbers as strings

Oops. I totally missed that you were doing that and should have caught it. For some reason I thought I'd checked that you *weren't* doing that, but apparently not.

**Comment by Zac-HD** [comment]
I was converting to work out what came next, but not to sort.  Anyway, #629.

**Pull request merged**
