### PR TITLE
Pin the version of uncompyle6

### PR DESCRIPTION
**Pull request by alexwlchan**
Related to #379 – there was an uncompyle6 version bump to 2.9.3 on October 26, so slightly after the bug started appearing (but timezones, so not sure).

I don’t think this should be merged yet, but opening this PR will trigger a bunch of runs against the Hypothesis CI with the pinned version. Let’s see if the issue still repros: if not, we’ve found the bug, if yes, I’ll keep cranking down the version.

### CODE REVIEW

**Comment by alexwlchan** [comment]
Ding, the Travis job just hit this bug, so it’s not this version of uncompyle6.

Let’s try downgrading further.

**Comment by alexwlchan** [comment]
🤔

Still broken if I go back to 2.8.x. Seems like it’s only failing on Python&nbsp;2 – time to go Py3k-only?

I’m out at the moment, but I’ll dig into the pattern when I get home.

**Comment by DRMacIver** [comment]
@alexwlchan uncompyle6 has a couple downstream dependencies. Could it be the version of one of those that matters instead?

Thanks for looking into this. ❤️

**Comment by alexwlchan** [comment]
Aha. uncompyle6 has two dependencies, spark-parser (last updated June 23rd) and xdis (last updated Oct 25th). And the original bug includes the new version of xdis. I wonder if that’s what‘s causing the problem. Let’s pin to an old version of xdis and see if we still get a repro.

**Comment by alexwlchan** [comment]
And rather helpfully, new versions of uncompyle6 require that you run the latest version of xdis.

/me adds another pin

**Comment by alexwlchan** [comment]
If this turns out to be a dependency issue (or even if it doesn’t), it seems like it might be worth having a CI task that runs whenever a dependency changes, so we spot breakages early.

I’ve seen https://requires.io on the hyper-h2 repo, not sure if that quite fits for Hypothesis but worth a look.

**Pull request closed without merging**
