### PR TITLE
Fix install on debian stable and release 3.7.2

### PR DESCRIPTION
**Pull request by DRMacIver**
Apparently #495 broke install on debian stable because people use ancient system provided pip and setuptools which can't handle wildcards in extras_require. 😭 

This PR:

* Fixes our test for old versions of pip to run the same version of setuptools and pip found in current debian stable (I verified manually that this reproduces the bug)
* Reverts #495 - I really doubt anyone is install hypothesis for django with the hypothesis[django] extra who does not already have django installed, so I think this is harmless.
* Updates the version and changelog (even though there is no code change so this is not required) so we can release 3.7.2 and fix that.

### CODE REVIEW

**Comment by DRMacIver** [comment]
>  Allowing install on Debian is more important than preventing people from unsupported testing against an EOL version of Django.

Welll... one of them creates more work for us and the other creates less work for us. I don't actually feel entirely good about the decision to support this mode of installation, but for the moment I'm inadequately convinced that we should drop it.

**Comment by Zac-HD** [comment]
> people use ancient system provided pip and setuptools which can't handle wildcards in extras_require

You think that's bad?  It turns `pip<9` will cheerfully upgrade you to a new package version that declares it doesn't support your version of Python.  That was fixed in *December 2016*, and without that fix it's impossible to package a release that drops Python 2 support without breaking something.

😭 😭 😭 indeed!

**Comment by DRMacIver** [comment]
> impossible 

Well you could always vendor an immutable version of the Python 2 version in your source tree and have a root package that checks if it's running on Python 2 and replaces itself with the vendored Python 2 version...

...

Look, I'm sorry, I have a problem. It's dangerous to use the word impossible around me, OK?

...

It'd work though. 😉

**Comment by DRMacIver** [comment]
Right. Lets see if this build automation thing works reliably or whether last time was just a fluke. 😅

**Pull request merged**
